name: PyPi Publish
on:
  release:
    types:
      - published
env:
  PYTHON_VERSION: "3.12"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: uv sync --frozen
      - name: Build and publish package
        run: uv publish
