name: PyPi Publish
on:
  release:
    types:
      - published
env:
  PYTHON_VERSION: "3.12"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: uv sync --frozen
      - name: Build and publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: "${{ secrets.PYPI_API_KEY }}"
        run: |
          uvx --from build pyproject-build --installer uv
          uvx twine upload dist/*
